#!/bin/bash
yum update
yum install git
yum install python3
curl -O https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py
yum install mysql
yum install mysql-devel
yum install gcc
yum install python3-devel
amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2
yum install -y httpd mariadb-server
systemctl start httpd
systemctl enable httpd
yum install mod_ssl
yum install mod_wsgi

